name: Publish Docker image

on:
  push:
    tags:
      - '*'
      - '**'

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Metadata
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: docker.io/bzeeman/sn_container

      - name: Push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
